DATASET: 
  NAME: "MiniDomainNetPseudo"
  SOURCE_DOMAINS: ["sketch"]
  
  TARGET_DOMAINS: ["painting"]
  NUM_SHOTS : 8


# you can modify the code to explore four domains
TEST:
  PER_CLASS_RESULT: True

TRAINER:
  FIXMATCH:
    STRONG_TRANSFORMS: ["randaugment_fixmatch"]