# INPUT:
#   SIZE: (224, 224)
#   TRANSFORMS: ["random_flip", "center_crop", "normalize"]

DATASET:
  NAME: "Office31Pseudo"
  SOURCE_DOMAINS: ["webcam"]
  
  TARGET_DOMAINS: ["amazon"]
  NUM_SHOTS : 8

# you can modify the code to explore four domains
TEST:
  PER_CLASS_RESULT: True

TRAINER:
  FIXMATCH:
    STRONG_TRANSFORMS: ["randaugment_fixmatch"]